### ISSUE TITLE
Any documentation for this?

### ISSUE THREAD

**Issue by bogordesaincom** [fomo-framework/framework#1]
Any documentation for this?

**Comment by amirfaramarzi** [comment]
No, unfortunately!

But the design is very similar to lumen and laravel

DB class is an instance of DB in Laravel
The Cache class is very similar to the Cache class in Laravel
The Elastic class is an instance of elastic/elasticsearch-php
The Forger class is an instance of fzaninotto/Faker
The JsonResource class is very similar to the JsonResource class in Laravel
The Log class is very similar to the Log class in Laravel
The Mail class is very similar to the Mail class in Laravel
The Queue class is very similar to the Queue class in Laravel
The Redis class is very similar to the Redis class in Laravel
The Response class is very similar to the Response class in Laravel
The TestCase class is very similar to the TestCase class in Laravel
The Validation class is very similar to the Validation class in Laravel

All classes have been tried to be programmed in the simplest possible way so that everyone can understand the code (with a small review in each class, you can understand how to use it)

In the end, due to lack of time, I cannot collect documentation for the tower. If you are willing to do so, I will be very happy.

**Comment by bogordesaincom** [comment]
I try using docker but show `Only run in command line mode` please how to use docker

**Comment by amirfaramarzi** [comment]
I haven't worked with docker much

I hope the following code will solve your problem

```
FROM php:8.1

RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install pcntl

RUN pecl install redis && docker-php-ext-enable redis

WORKDIR /var/www/html/

COPY ./ /var/www/html

EXPOSE 9000

ENTRYPOINT [ "php", "server.php" ]

CMD [ "start" ]
```
